DROP TABLE IF EXISTS Prepare;
DROP TABLE IF EXISTS Ordered_By;
DROP TABLE IF EXISTS Food_Order;
DROP TABLE IF EXISTS cuisine;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Staff;
DROP TABLE IF EXISTS Cook;
DROP TABLE IF EXISTS Member;